# ===================================================
# BACKUP NETLIFY CONFIG - Sin validación de variables
# ===================================================
# 
# USAR SOLO SI EL BUILD PRINCIPAL FALLA
# 
# Para usarlo:
# 1. Renombrar netlify.toml a netlify-with-validation.toml
# 2. Renombrar este archivo a netlify.toml
# 3. Trigger deploy
# 4. Agregar variables de entorno en Netlify Dashboard
# 5. Restaurar la configuración original
#

[build]
  # Build sin validación (TEMPORAL)
  command = "vite build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Special headers for HTML files (shorter cache)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Special headers for service worker (no cache)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirect rules
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 