// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Simple validation with enhanced error reporting
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('🚨 SUPABASE ENV VARS DEBUG:');
  console.error('- VITE_SUPABASE_URL:', SUPABASE_URL || 'MISSING');
  console.error('- VITE_SUPABASE_ANON_KEY:', SUPABASE_ANON_KEY || 'MISSING');
  console.error('- All env vars:', import.meta.env);
  console.error('- VITE_ vars:', Object.keys(import.meta.env).filter(k => k.startsWith('VITE_')));
  
  throw new Error(`Missing Supabase environment variables. Check console for debug info.`);
}

console.log('✅ Supabase environment variables found successfully');

// Create and export the client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    }
  }
});