// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseURL, getSupabaseAnonKey } from '../../hooks/temp-fix';

// TEMPORARY: Debug logging for production troubleshooting - REMOVE AFTER FIXING
console.log('🔍 SUPABASE CLIENT DEBUG (PRODUCTION):');
console.log('- MODE:', import.meta.env.MODE);
console.log('- DEV:', import.meta.env.DEV);

let SUPABASE_URL: string;
let SUPABASE_PUBLISHABLE_KEY: string;

try {
  SUPABASE_URL = getSupabaseURL();
  SUPABASE_PUBLISHABLE_KEY = getSupabaseAnonKey();
  
  console.log('- VITE_SUPABASE_URL exists:', !!SUPABASE_URL);
  console.log('- VITE_SUPABASE_URL value:', SUPABASE_URL ? `${SUPABASE_URL.substring(0, 40)}...` : 'MISSING');
  console.log('- VITE_SUPABASE_ANON_KEY exists:', !!SUPABASE_PUBLISHABLE_KEY);
  console.log('- VITE_SUPABASE_ANON_KEY value:', SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...` : 'MISSING');
  console.log('- All import.meta.env keys:', Object.keys(import.meta.env));
  console.log('- All VITE_ keys:', Object.keys(import.meta.env).filter(key => key.startsWith('VITE_')));

  // Validate URL format
  if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_URL.includes('.supabase.co')) {
    throw new Error(`Invalid VITE_SUPABASE_URL format. Expected: https://your-project.supabase.co, got: ${SUPABASE_URL}`);
  }

  // Validate anon key format
  if (!SUPABASE_PUBLISHABLE_KEY.startsWith('eyJ')) {
    throw new Error(`Invalid VITE_SUPABASE_ANON_KEY format. Key should start with 'eyJ', got: ${SUPABASE_PUBLISHABLE_KEY.substring(0, 10)}...`);
  }

  console.log('✅ SUPABASE CLIENT: Environment variables validated successfully');

} catch (error) {
  console.error('🚨 SUPABASE CLIENT: Environment validation failed:', error);
  
  // Enhanced error message with troubleshooting info
  const errorMessage = `Missing or invalid Supabase environment variables.

🔧 TROUBLESHOOTING STEPS:

1. Check Netlify Environment Variables:
   - Go to Site Settings → Environment variables
   - Ensure these exact names exist: VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY
   - Variables must have VITE_ prefix for frontend access

2. Verify Deploy Context:
   - Variables must be set for both Production and Deploy Preview
   - Check current deploy context in Netlify dashboard

3. Force New Deploy:
   - Trigger a new build (don't just redeploy)
   - Environment variables are embedded at build time

4. Check Variable Format:
   - VITE_SUPABASE_URL: https://your-project.supabase.co (no trailing slash)
   - VITE_SUPABASE_ANON_KEY: Should start with 'eyJ'

Current environment: ${import.meta.env.MODE}
Available VITE_ variables: ${Object.keys(import.meta.env).filter(key => key.startsWith('VITE_')).join(', ') || 'None found'}

Original error: ${error instanceof Error ? error.message : String(error)}`;

  throw new Error(errorMessage);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    }
  }
});